version: '2'

services:
  spark:
    image: huyaoban/spark-hadoop:3
    hostname: master
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    volumes:
      - ~/docker/spark/share:/opt/share
    networks:
      spark-hadoop:
        ipv4_address: 172.21.0.2
  spark-worker-1:
    image: huyaoban/spark-hadoop:3
    hostname: worker1
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://master:7077
      - SPARK_WORKER_MEMORY=4G
      - SPARK_WORKER_CORES=2
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      # - SPARK_SSL_ENABLED=yes
      # - SPARK_SSL_KEY_PASSWORD=KEY_PASSWORD
      # - SPARK_SSL_KEYSTORE_PASSWORD=KEYSTORE_PASSWORD
      # - SPARK_SSL_TRUSTSTORE_PASSWORD=TRUSTSTORE_PASSWORD
      # - SPARK_SSL_NEED_CLIENT_AUTH=yes
      # - SPARK_SSL_PROTOCOL=TLSv1.2
    volumes:
      - ~/docker/spark/share:/opt/share
    networks:
      spark-hadoop:
        ipv4_address: 172.21.0.3
  spark-worker-2:
    image: huyaoban/spark-hadoop:3
    hostname: worker2
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://master:7077
      - SPARK_WORKER_MEMORY=4G
      - SPARK_WORKER_CORES=2
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      # - SPARK_SSL_ENABLED=yes
      # - SPARK_SSL_KEY_PASSWORD=KEY_PASSWORD
      # - SPARK_SSL_KEYSTORE_PASSWORD=KEYSTORE_PASSWORD
      # - SPARK_SSL_TRUSTSTORE_PASSWORD=TRUSTSTORE_PASSWORD
      # - SPARK_SSL_NEED_CLIENT_AUTH=yes
      # - SPARK_SSL_PROTOCOL=TLSv1.2
    volumes:
      - ~/docker/spark/share:/opt/share
    networks:
      spark-hadoop:
        ipv4_address: 172.21.0.4
networks:
  spark-hadoop:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.21.0.0/24
